# General settings
title: Anna Walsdorff
# title_html: "<b>ga</b>briel<b><span class=\"invisible\"> </span>alcaras</b>"
description:
  en: PhD student working on development finance and quantitative methods. Data nerd.
baseurl: ""
# url: "https://gaalcaras.com"

langs: ["en"]
# defaults:
#  - scope:
#      path: ""
#    values:
#      lang: "en"

# Author
author: Anna Walsdorff

email: anna.walsdorff@gmail.com
twitter_username: lavendeleis
github_username: ffrodslaw
# keybase_username: gaalcaras
# linkedin_username: gaalcaras
# author_website: https://sociologs.com
curriculum:
 # url: assets/cv_gaalcaras.pdf

# Nav menu
# nav_ext_links:
 # - name: Blog
 #   url:
 #     fr: https://sociologs.com/fr/
 #     en: https://sociologs.com/en/

# Piwik
piwik:
  url: batcloud.me/piwik
  site_id: 2

# Favicon
favicon:
  safari: 5bbad5
  theme: ffffff

# Build settings
markdown: kramdown
redcarpet:
  extensions: ["tables", "fenced_code_blocks", "autolink", "footnotes", "with_toc_data"]
theme: academic
gems:
  - jekyll-feed
exclude:
  - jekyll_build.sh
  - Gemfile
  - Gemfile.lock
